### ISSUE TITLE
Is P2SH Possible for this wallet implementation?

### ISSUE THREAD

**Issue by taariq** [SF-Bitcoindevs/bitcoinjslib-wallet#14]
Hey @sidazhang how hard would it be for us to consider implementing P2SH in our wallet?  I think it might be just too hard, but I thought I'd ask.

**Comment by sidazhang** [comment]
what do you mean implement p2sh. Do you mean the ability to send to a p2sh address? Or do you mean the ability to have a p2sh address in the wallet

**Comment by taariq** [comment]
I'm thinking the ability to have a P2SH in the wallet. Sending to a P2SH
would be as simple as using the send functionality. Yes?

**Comment by sidazhang** [comment]
there is a little extra work to send to a p2sh address. but it is not hard

To have a p2sh address means there needs to be some kind of server side component. (thus that is how we keep the funds safe - by having one key somewhere else)

How do you feel about having server side component?

**Comment by taariq** [comment]
Interesting. Yeah, I don't feel good about having a server side component for our first version. However, paying to a P2SH means that it's possible to pay to all types of IsStandard transactions. Okay, I'll close this as possible feature, but "it is not hard".

**Comment by sidazhang** [comment]
I think the answer is to have the ability to send. 

Having a P2SH address is a little different. The server side component that is required is the remote signer as it can make the wallet substantially more secure. 

http://gavintech.blogspot.com/2012/03/bitcoin-faucet-hacked.html

**Comment by taariq** [comment]
Yes. I agree that having the ability to send is a nice way to let folks know they can send to multisig addresses that are P2SH transactions. Thanks for the link to Gavin's post.
