### ISSUE TITLE
DECRYPT YOUR WALLET PASSPHRASE is confusing the original design

### ISSUE THREAD

**Issue by taariq** [SF-Bitcoindevs/bitcoinjslib-wallet#22]
I am not sure what "DECRYPT YOUR WALLET PASSPHRASE" is supposed to do for this design of the web wallet.

I think for the SF Bitcoin dev wallet, we should leave the basic functionality of carbon wallet. Password management for decryption is really something for the DTT product which may be out of scope for this general project. Thoughts?

**Comment by ssr1ram** [comment]
I haven't done much testing... BUT... it looks like the passphrase breaks when one tries to generate a link AND Open Wallet after logout also breaks. There is no reason either of these needs to be in the product.

**Comment by taariq** [comment]
@ssr1ram a little confused. There are 2 input boxes now on app.html. Was the second one always in the code? I didn't check. Can we revert back to the original input or create a passprhase? You want me to open up an issue for Open wallet after logout breaking?

**Comment by taariq** [comment]
Issue with JS. Will open separate isseu.
