### ISSUE TITLE
App.html HTML looks mangled. Is this because of jade?

### ISSUE THREAD

**Issue by taariq** [SF-Bitcoindevs/bitcoinjslib-wallet#23]
Hey Srirarm. the HTML in app.html looks like it's lost all its formatting and is now fed as one whole block of text. Is this because of Jade?  Can we revert back to clean looking html in the app.html file?

**Comment by ssr1ram** [comment]
Yes we can, would need to compile with the -P (for pretty) switch.
Will get to it later.

**Comment by taariq** [comment]
If you have any documentation that I could look at, I could review right now
and take a look.

**Comment by ssr1ram** [comment]
I've fixed the Gruntfile.js on the repo - so pretty:true now works

**Comment by taariq** [comment]
+1 Thanks!
