### ISSUE TITLE
When I click "Make a Payment" the balance on my Source address is not current balance

### ISSUE THREAD

**Issue by taariq** [SF-Bitcoindevs/bitcoinjslib-wallet#24]
When I click "Make a Payment" the balance on my Source address is not current balance. 

Using testnet. Open wallet about 3x so my testnet balance increases to 0.0156. However, my balance still says 0.003 which was my first balance when I  created the wallet.

**Comment by lkang** [comment]
In WALLET.updateAllBalances() the faucet is being tapped _after_ retrieving account balances. Probably would be better to make the faucet a separate button and then update balances? (nvm, this is not how it worked, I misread the code)

**Comment by lkang** [comment]
"add" button on first address can be pressed 3x.

**Comment by taariq** [comment]
Sweet!
