### ISSUE TITLE
Miner Fee field should be editable. 

### ISSUE THREAD

**Issue by taariq** [SF-Bitcoindevs/bitcoinjslib-wallet#25]
Miner fee is currently fixed at 0.0005. The miner fee should be editable so that users can choose any fee they wish.

**Comment by lkang** [comment]
fyi currently the code sends 0.0001 and at one point the UI used to match. I agree that editable is better.

**Comment by lkang** [comment]
not editable yet, but shows 0.0001

**Comment by lkang** [comment]
now it's editable

**Comment by taariq** [comment]
Thanks. Testing now.

**Comment by taariq** [comment]
ACK
