### ISSUE TITLE
WALLET.keys doesn't clear on logout

### ISSUE THREAD

**Issue by karlkeefer** [SF-Bitcoindevs/bitcoinjslib-wallet#34]
Presumably you don't want those available after logout.

**Comment by taariq** [comment]
Oh dearie my. Yeah, we don't want those available after logout! Good catch.

**Comment by taariq** [comment]
@lkang any way we can clear this one out on logout?

**Comment by lkang** [comment]
yes, simple one liner. I'll do it tonight

**Comment by taariq** [comment]
You are such a tease! :-)

**Comment by lkang** [comment]
https://github.com/SF-Bitcoindevs/bitcoinjslib-wallet/pull/39
