### ISSUE TITLE
remove helloblock.js and use the official client library

### ISSUE THREAD

**Issue by sidazhang** [SF-Bitcoindevs/bitcoinjslib-wallet#38]
I would like to recommend to remove this file https://github.com/SF-Bitcoindevs/bitcoinjslib-wallet/blob/master/js/helloblock.js

And replace with the official client lib which is maintained actively. https://github.com/helloblock/helloblock-js

It is best to use the client lib as it is well tested and covers every single endpoint.

**Comment by taariq** [comment]
Sounds like a good move! You okay to switch us over, @sidazhang?

**Comment by m0llusk** [comment]
Using the official client library is best, but it appears that these interfaces do not match up exactly.  While bitcoinjslib-wallet/js/helloblock.js implements retrieveAllBalances, getUnspentOutputs, sendTX, and faucetWithdrawl, the helloblock-js/lib/helloblock.js defines different interfaces with Transaction, Address, Block, Faucet, and Wallet broken out separately.  Possibly this could be changed over by using Address.prototype.batchGet, Address.prototype.getUnspents, Transaction,prototype.propagate, and Faucet.prototype.withdraw, but this is probably a significant change that would require some care.

**Comment by taariq** [comment]
Thanks @m0llusk. @sidazhang What's the word here? You overloading us lazy folks with more work brah? How do we reconcile the diffs that Christian brings up above?

**Comment by sidazhang** [comment]
The fast way to go about this would be to replace the internals of helloblock.js to be backed by the official client lib. 

For example:

``` js
this.retrieveAllBalances = function(addresses, callback) {
   helloblock.addresses.batchGet(addresses, callback)
 }

```

This way there will be no change to the interface but you get all the benefit of the actively maintained client lib. 

Otherwise, I would recommend investing the time to switch over. It is not essential to switch as the API is version locked. But official client lib will be more extensible when you would like to add functionalities to the wallet in the future.

**Comment by taariq** [comment]
I'll try to work on this today. @lkang any interest in helping out on this one?

**Comment by lkang** [comment]
Sure!

**Comment by taariq** [comment]
@karlkeefer This was the issue I was referring to, today.

**Comment by taariq** [comment]
Thanks @m0llusk! closing!

**Comment by m0llusk** [comment]
I'm no longer sure this is possible or even desirable.  At first it seemed this was just a new version of helloblock with some new features.  It appears, however, that this is a whole new architecture that gets flexibility and functionality from use of a great many modules.

This starts with the basic architecture that uses require.js to dynamically include submodules to handle all of the actual work: addresses.js, blocks.js, client.js. faucet.js, transactions.js, and wallet.js.  In turn these submodules require other modules: util.js, underscore.js, request.js, querystring.js, and log.js.  These seems reasonable, and util.js and log.js were already present.

Unfortunately there are complications.  Things really blow up when client.js from helloblock requires request.js which is a an HTTP client implementation.  The request module then requires http, url, util, stream, qs, crypto, node-uuid, mime, json-stringify-safe, forever-agent, net, in addition to its own submodules cookies, copy, copy, debug, getSafe, and optional.  The optional module is kind of like require, but more subtle.  It is used to optionally make use of https, tls, oauth, hawk, aws, http-signature, tunnel-agent, and form-data.  Apart from the request.js submodules these modules are all node modules that may not be intended for use in a browser.

In addition to complicating possible usage this large number of modules introduces a large number of open issues and failure modes.  The request.js module alone has around 300 open issues.  While the latest version of helloblock may be much more modular and flexible and powerful than the previous version used, it is not simple to use in a browser application and may introduce a large number of potential problems.

**Comment by taariq** [comment]
@sidazhang you giving us more work brah?

**Comment by taariq** [comment]
Thanks for the analysis @m0llusk. Nice work.

**Comment by sidazhang** [comment]
Thanks for the raising that up. Although I don't think that is actually relevant. Because you don't actually use the `request` module.

`helloblock-js` is both browser compatible as well as nodejs compatible. Which means it has 2 http request dependency and depending on which environment you are running this. It uses a different module. 

Since this is a browser-side wallet, when you use browserify to compile your code, the `request` module is actually not included at all.

When you compile for browser, only the `browser-request` dependency is required. See here:
https://github.com/helloblock/helloblock-js/blob/master/package.json#L25

**Comment by sidazhang** [comment]
`request` module is not compatible with browser-side applications. `browser-request` is implemented with `AJAX` behind the scene so it is compatible
